[package]
name = "mosaik-rust-api"
version = "0.1.0"
authors = ["caemor"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.41"
# jsonrpc-core = "15.1.0"
# jsonrpc-http-server = "15.1.0"
# json = "*"
serde_json = "1.0.59"
json = "*"
futures = "0.3.8"
async-std = "1"
log = "0.4.11"
thiserror = "1.0.22"
