[package]
name = "mosaik-rust-api"
version = "0.1.0"
authors = ["Jakob Pohl", "Christoph Gross"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
enerdag-marketplace = {path = "../enerdag/enerdag-marketplace"}
enerdag-crypto = {path = "../enerdag/enerdag-crypto"}

[dependencies]
structopt = "0.3"
async-trait = "0.1.41"
serde_json = "1.0.59"
futures = "0.3.8"
async-std = "1"
log = "0.4.11"
env_logger = "0.8.2"
thiserror = "1.0.22"
