[package]
name = "mosaik-rust-api"
version = "0.1.0"
authors = ["caemor"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.41"
jsonrpc-core = "4.0"